// File generated by FlutterFire CLI - MODIFIED FOR SECURITY.
// Gercek API key'ler ASLA bu dosyaya hardcoded yazilmaz.
// Degerler `--dart-define` ile build/run zamaninda verilir.
//
// Yerel calistirma:
//   flutter run --dart-define-from-file=.env.local
// veya VS Code'da F5 (bkz. .vscode/launch.json, FIREBASE_SETUP.md)
//
// CI/CD: GitHub Secrets -> --dart-define olarak gec.
//
// Bu dosya GitHub'a push'lanabilir cunku icinde secret YOKTUR.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Degerler `--dart-define` ile gelir. Eksikse anlamli hata firlatir.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Ortak, secret olmayan degerler sabit kalabilir.
  // Bunlar tek basina bir ise yaramaz, API key olmadan Firebase calismaz.
  static const String _messagingSenderId = '912252919494';
  static const String _projectId = 'ulakchatapp-3198a';
  static const String _storageBucket = 'ulakchatapp-3198a.firebasestorage.app';
  static const String _authDomain = 'ulakchatapp-3198a.firebaseapp.com';

  // KRİTİK DART KURALI: `String.fromEnvironment()` YALNIZCA const literal
  // ile çağrıldığında derleyici tarafından doldurulur!
  // Eski `_req(String name)` fonksiyonu parametreyle çağırıyordu
  // (`String.fromEnvironment(name)`), bu yüzden HER ZAMAN "" dönüyordu
  // ve uygulama sürekli "Firebase kurulumu eksik" ekranını gösteriyordu.
  // Bu yüzden her getter kendi const key adını doğrudan yazar.
  static Never _missing(String name) {
    throw StateError(
      '$name Missing --dart-define. FIREBASE_SETUP.md dosyasina bakip '
      '.env.local olusturun veya launch.json ile calistirin.',
    );
  }

  static FirebaseOptions get web {
    const opts = FirebaseOptions(
      apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
      appId: '1:912252919494:web:a631ad4eee0bdf276c01c7',
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      authDomain: _authDomain,
      storageBucket: _storageBucket,
    );
    if (opts.apiKey.isEmpty) _missing('FIREBASE_WEB_API_KEY');
    return opts;
  }

  static FirebaseOptions get android {
    const opts = FirebaseOptions(
      apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY'),
      appId: '1:912252919494:android:6e85121b12bec2b16c01c7',
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      storageBucket: _storageBucket,
    );
    if (opts.apiKey.isEmpty) _missing('FIREBASE_ANDROID_API_KEY');
    return opts;
  }

  static FirebaseOptions get ios {
    const opts = FirebaseOptions(
      apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
      appId: '1:912252919494:ios:5023ec09ffad64fa6c01c7',
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      storageBucket: _storageBucket,
      iosBundleId: 'com.example.ulakchatapp',
    );
    if (opts.apiKey.isEmpty) _missing('FIREBASE_IOS_API_KEY');
    return opts;
  }

  static FirebaseOptions get macos {
    const opts = FirebaseOptions(
      apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY'),
      appId: '1:912252919494:ios:5023ec09ffad64fa6c01c7',
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      storageBucket: _storageBucket,
      iosBundleId: 'com.example.ulakchatapp',
    );
    if (opts.apiKey.isEmpty) _missing('FIREBASE_IOS_API_KEY');
    return opts;
  }

  static FirebaseOptions get windows {
    const opts = FirebaseOptions(
      apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY'),
      appId: '1:912252919494:web:e16c6acd686770da6c01c7',
      messagingSenderId: _messagingSenderId,
      projectId: _projectId,
      authDomain: _authDomain,
      storageBucket: _storageBucket,
    );
    if (opts.apiKey.isEmpty) _missing('FIREBASE_WEB_API_KEY');
    return opts;
  }
}
