// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REDACTED_WEB_KEY***',
    appId: '1:912252919494:web:a631ad4eee0bdf276c01c7',
    messagingSenderId: '912252919494',
    projectId: 'ulakchatapp-3198a',
    authDomain: 'ulakchatapp-3198a.firebaseapp.com',
    storageBucket: 'ulakchatapp-3198a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REDACTED_ANDROID_KEY***',
    appId: '1:912252919494:android:6e85121b12bec2b16c01c7',
    messagingSenderId: '912252919494',
    projectId: 'ulakchatapp-3198a',
    storageBucket: 'ulakchatapp-3198a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REDACTED_IOS_KEY***',
    appId: '1:912252919494:ios:5023ec09ffad64fa6c01c7',
    messagingSenderId: '912252919494',
    projectId: 'ulakchatapp-3198a',
    storageBucket: 'ulakchatapp-3198a.firebasestorage.app',
    iosBundleId: 'com.example.ulakchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '***REDACTED_IOS_KEY***',
    appId: '1:912252919494:ios:5023ec09ffad64fa6c01c7',
    messagingSenderId: '912252919494',
    projectId: 'ulakchatapp-3198a',
    storageBucket: 'ulakchatapp-3198a.firebasestorage.app',
    iosBundleId: 'com.example.ulakchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '***REDACTED_WEB_KEY***',
    appId: '1:912252919494:web:e16c6acd686770da6c01c7',
    messagingSenderId: '912252919494',
    projectId: 'ulakchatapp-3198a',
    authDomain: 'ulakchatapp-3198a.firebaseapp.com',
    storageBucket: 'ulakchatapp-3198a.firebasestorage.app',
  );
}
